export const colors = {
    leftNavBgColor: "#1a2f4e",
    topNavBgColor: "#ffffff",
    bgColor: "#ffffff",
    linksColor: "#ffffff",
    linkSectionsColor: "#4a5f7f",
    profileNameColor: "#ffffff",
    profileUserTypeColor: "#d4a574",
    topNavColor: "#1a2f4e",
    mainBgColor: "#f5f7fa",
    mainMainHeadings: "#1a2f4e",
    mainProgressSteps: "#4a5f7f",
    mainProgressStepDone: "#1a2f4e",
    mainProgressStepActive: "#d4a574",
    mainProgressStepPending: "#4a5f7f",
    mainProgressStepSubItems: "#1a2f4e",
    mainLabelsText: "#4a5f7f",
    mainInputsBorderNotDone: "#1a2f4e",
    mainInputsBorderDone: "#d4a574",
    mainButtonPrev: "#4a5f7f",
    mainButtonNext: "#1a2f4e",
    gradientStartColor: "#f5f7fa",
    gradientEndColor: "#e8d5c4"
}