export const colors = {
    leftNavBgColor: "#17314dff",
    topNavBgColor: "#ffffff",
    bgColor: "#ffffff",
    linksColor: "#ffffff",
    linkSectionsColor: "#E5E7EB",
    profileNameColor: "#ffffff",
    profileUserTypeColor: "#ffffff",
    topNavColor: "#020527ff",
    mainBgColor: "#ffffff",
    mainMainHeadings: "#1E1B4B",
    mainProgressSteps: "#4338CA",
    mainProgressStepDone: "#1E1B4B",
    mainProgressStepActive: "#4338CA",
    mainProgressStepPending: "#1E1B4B",
    mainProgressStepSubItems: "#1E1B4B",
    mainLabelsText: "#1E1B4B",
    mainInputsBorderNotDone: "#1E1B4B",
    mainInputsBorderDone: "#ffffff",
    mainButtonPrev: "#000000",
    mainButtonNext: "#312E81",
    gradientStartColor: "#e9c6e1ff",
    gradientEndColor: "#dcd9edff"
}